=== solidjs/solidex/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "EcosystemType": {
            "enum": [
                "article",
                "package",
                "podcast",
                "video"
            ],
            "type": "string"
        }
    },
    "properties": {
        "author": {
            "type": "string"
        },
        "author_url": {
            "type": "string"
        },
        "categories": {
            "items": {
                "enum": [
                    "add_on",
                    "build_utility",
                    "data",
                    "educational",
                    "plugin",
                    "primitive",
                    "router",
                    "starters",
                    "testing",
                    "ui"
                ],
                "type": "string"
            },
            "type": "array"
        },
        "description": {
            "type": "string"
        },
        "keywords": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "link": {
            "format": "uri",
            "type": "string"
        },
        "official": {
            "type": "boolean"
        },
        "published_at": {
            "format": "date-time",
            "type": "string"
        },
        "title": {
            "minLength": 1,
            "type": "string"
        },
        "type": {
            "$ref": "#/definitions/EcosystemType"
        }
    },
    "type": "object"
}

=== solidjs/solidex/data/article/alternatives-to-react-solid-js.json
{
  "link": "https://blog.openreplay.com/alternatives-to-react-solid-js",
  "title": "Alternatives to React: Solid JS",
  "description": "Alternatives to React is a series of articles looking at different JavaScript front-end frameworks.",
  "author": "Amazing Enyichi Agu",
  "author_url": "https://blog.openreplay.com/authors/amazing-enyichi-agu",
  "keywords": [
    "ui",
    "alternatives",
    "react"
  ],
  "type": "article",
  "categories": [
    "educational"
  ],
  "published_at": "2022-06-22T04:28:50.000Z"
}

=== solidjs/solidex/data/podcast/solidjs-with-ryan-carniato---jsj-528.json
{
  "title": "SolidJS with Ryan Carniato - JSJ 528",
  "link": "https://javascriptjabber.com/solidjs-with-ryan-carniato-jsj-528",
  "description": "SolidJS is a web development framework that focuses on using reactivity and carries forward several ideas from Knockout.js.",
  "author": "JavascriptJabber",
  "author_url": "https://javascriptjabber.com/",
  "keywords": [
    "javascript",
    "jabber",
    "knockout",
    "reactivity"
  ],
  "type": "podcast",
  "categories": [
    "educational"
  ],
  "published_at": "2022-04-22T16:59:26.000Z"
}

=== solidjs/solidex/data/package/solid-i18n.json
{
  "link": "https://github.com/SanichKotikov/solid-i18n",
  "title": "solid-i18n",
  "description": "Tiny translation library for solid-js inspired by Rosetta.",
  "author": "SanichKotikov",
  "author_url": "https://github.com/SanichKotikov",
  "keywords": [
    "i18n",
    "localisation",
    "localization",
    "translate",
    "translations",
    "language",
    "rosetta"
  ],
  "official": false,
  "type": "package",
  "categories": [
    "plugin",
    "ui"
  ],
  "published_at": "2021-10-31T16:23:52.000Z"
}

=== solidjs/solidex/data/article/solid-vs-react---the-fastest-vs-the-most-popular-ui-library.json
{
  "link": "https://blog.openreplay.com/solid-vs-react-the-fastest-vs-the-most-popular-ui-library",
  "title": "Solid vs React - the Fastest VS the Most Popular UI Library",
  "description": "An article presented by OpenReplay discussing the differences between React and Solid.",
  "author": "Arek Nawo",
  "author_url": "https://blog.openreplay.com/authors/arek-nawo",
  "keywords": [
    "react",
    "solid",
    "comparison"
  ],
  "type": "article",
  "categories": [
    "educational"
  ],
  "published_at": "2021-06-28T00:00:00.000Z"
}

=== solidjs/solidex/data/article/solidjs---a-first-look.json
{
  "link": "https://codechips.me/solidjs-first-look/",
  "title": "SolidJS - a first look",
  "description": "Ilia takes SolidJS for a spin and compare it to Svelte in terms of DevX",
  "author": "Ilia Mikhailov",
  "author_url": "https://codechips.me/",
  "keywords": [
    "mikhailov",
    "svelte",
    "codechips",
    "transitions"
  ],
  "type": "article",
  "categories": [
    "educational"
  ],
  "published_at": "2021-07-20T00:00:00.000Z"
}

=== solidjs/solidex/data/video/solidjs-intro-in-5-minutes-for-react-developers.json
{
  "link": "https://www.youtube.com/watch?v=JWcorrKWRgY",
  "title": "SolidJS Intro in 5 minutes (for React Developers)",
  "description": "SolidJS is a \"new\" (5 years old) UI library with an API very similar to React that is gaining more and more popularity on Twitter and GitHub (20k stars), and which, in my opinion, is exactly how React should work.",
  "keywords": [
    "solid",
    "introduction",
    "5-minutes",
    "react"
  ],
  "author": "Fabio Biondi",
  "author_url": "https://www.youtube.com/c/FabioBiondi",
  "type": "video",
  "categories": [
    "educational"
  ],
  "published_at": "2022-05-27T21:00:00.000Z"
}

=== solidjs/solidex/data/package/fastify-dx-solid.json
{
  "link": "https://github.com/fastify/fastify-dx/tree/main/packages/fastify-dx-solid",
  "title": "fastify-dx-solid",
  "description": "Fastify DX for Solid is a renderer adapter for fastify-vite.",
  "author": "Fastify",
  "author_url": "https://github.com/fastify",
  "keywords": [
    "full stack",
    "fastify",
    "framework",
    "server",
    "back-end"
  ],
  "official": false,
  "type": "package",
  "categories": [
    "ui"
  ]
}

=== solidjs/solidex/data/package/solid-hcaptcha.json
{
  "link": "https://github.com/Vexcited/solid-hcaptcha",
  "title": "solid-hcaptcha",
  "description": "hCaptcha Component Library for Solid.",
  "author": "Mikkel Ringaud",
  "author_url": "https://github.com/Vexcited",
  "keywords": [
    "hcaptcha",
    "captcha"
  ],
  "official": false,
  "type": "package",
  "categories": [
    "plugin"
  ]
}
