=== solidjs/solidex/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "EcosystemType": {
            "enum": [
                "article",
                "package",
                "podcast",
                "video"
            ],
            "type": "string"
        }
    },
    "properties": {
        "author": {
            "type": "string"
        },
        "author_url": {
            "type": "string"
        },
        "categories": {
            "items": {
                "enum": [
                    "add_on",
                    "build_utility",
                    "data",
                    "educational",
                    "plugin",
                    "primitive",
                    "router",
                    "starters",
                    "testing",
                    "ui"
                ],
                "type": "string"
            },
            "type": "array"
        },
        "description": {
            "type": "string"
        },
        "keywords": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "link": {
            "format": "uri",
            "type": "string"
        },
        "official": {
            "type": "boolean"
        },
        "published_at": {
            "format": "date-time",
            "type": "string"
        },
        "title": {
            "minLength": 1,
            "type": "string"
        },
        "type": {
            "$ref": "#/definitions/EcosystemType"
        }
    },
    "type": "object"
}

=== solidjs/solidex/data/article/why-solidjs-do-we-really-need-another-js-ui-library.json
{
  "link": "https://dev.to/ryansolid/why-solidjs-do-we-need-another-js-ui-library-1mdc",
  "title": "Why SolidJS: Do We Really Need Another JS UI Library",
  "description": "Ryan's personal journey creating SolidJS.",
  "author": "Ryan Carniato",
  "author_url": "https://www.github.com/ryansolid",
  "keywords": [
    ""
  ],
  "type": "article",
  "categories": [
    "educational"
  ],
  "published_at": "2020-06-01T07:07:47.000Z"
}

=== solidjs/solidex/data/video/the-story-of-solid-js-and-how-its-different.json
{
  "link": "https://www.youtube.com/watch?v=O4sgwuMQns0",
  "title": "The story of Solid JS and How its Different",
  "description": "Ryan joins ThePrimeagen to discuss Solid and where it has come from.",
  "keywords": [
    "history",
    "story",
    "solid",
    "ryan"
  ],
  "author": "ThePrimaegen",
  "author_url": "https://www.youtube.com/c/ThePrimeagen",
  "type": "video",
  "categories": [
    "educational"
  ],
  "published_at": "2022-06-03T17:24:36.000Z"
}

=== solidjs/solidex/data/package/lit-dom-expressions.json
{
  "link": "https://github.com/ryansolid/dom-expressions/tree/main/packages/lit-dom-expressions",
  "title": "lit-dom-expressions",
  "description": "Tagged Template Literal API for DOM Expressions.",
  "author": "Ryan Carniato",
  "author_url": "https://github.com/ryansolid",
  "keywords": [
    "babel",
    "expressions"
  ],
  "official": false,
  "type": "package",
  "categories": [
    "build_utility"
  ]
}

=== solidjs/solidex/data/package/solid-urql.json
{
  "link": "https://www.npmjs.com/package/solid-urql",
  "title": "solid-urql",
  "description": "A highly customizable and versatile GraphQL client for Solid.",
  "author": "Ari Seyhun",
  "author_url": "https://github.com/Acidic9",
  "keywords": [
    "graphql",
    "url",
    "url",
    "formidable"
  ],
  "official": false,
  "type": "package",
  "categories": [
    "data"
  ]
}

=== solidjs/solidex/data/package/solid-storeon.json
{
  "link": "https://github.com/storeon/solidjs",
  "title": "solid-storeon",
  "description": "A package that helps to connect store with Solid.js to provide a better performance and developer experience while remaining so tiny.",
  "author": "Storeon",
  "keywords": [
    "storeon",
    "store"
  ],
  "official": false,
  "type": "package",
  "categories": [
    "add_on",
    "data"
  ]
}

=== solidjs/solidex/data/video/solidjs-with-ryan-carniato.json
{
  "link": "https://www.youtube.com/watch?v=70w-UoEu3Ss",
  "title": "SolidJS with Ryan Carniato",
  "description": "Ryan Carniato tells us all about SolidJS, a declarative, efficient, and flexible JavaScript library for building user interfaces.",
  "keywords": [
    "logrocket",
    "solid",
    "react",
    "module",
    "federation"
  ],
  "author": "LogRocket",
  "author_url": "https://www.youtube.com/channel/UCktI_HQAkbr-tJbdWnQ_osw",
  "type": "video",
  "categories": [
    "educational"
  ],
  "published_at": "2021-09-01T07:51:41.000Z"
}

=== solidjs/solidex/data/video/reactive-primitives-in-solid-js.json
{
  "link": "https://www.youtube.com/watch?v=wre8TPir36s",
  "title": "Reactive Primitives in Solid JS",
  "description": "This video is about different SolidJS reactive primitives. How to use them in a an application.",
  "keywords": [
    "intro",
    "primitives"
  ],
  "author": "dotJS",
  "author_url": "https://www.youtube.com/channel/UCcSeQUrdrNObZqyqMD-913g",
  "type": "video",
  "categories": [
    "educational",
    "primitive"
  ],
  "published_at": "2021-11-25T03:26:10.000Z"
}

=== solidjs/solidex/data/video/pourquoi-solid-js-vs-react--svelte.json
{
  "link": "https://www.youtube.com/watch?v=4Xnt2ASdFbA",
  "title": "Pourquoi Solid JS (vs React & Svelte)?",
  "description": "Solid JS ressemble en surface à React, et sous la surface, à Svelte. Qu'apporte ce framework de plus que la pléthoire de frameworks qui existent déjà, ou que le framework dominant qu'est React ?",
  "keywords": [
    "solid",
    "introduction",
    "react",
    "svelte",
    "comparison",
    "fr"
  ],
  "author": "Kodaps - apprendre à coder",
  "author_url": "https://www.youtube.com/channel/UCzdX32OIhpfrdxQRhN2s98w",
  "type": "video",
  "categories": [
    "educational"
  ],
  "published_at": "2022-05-26T21:00:00.000Z"
}
