=== solidjs/solidex/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "EcosystemType": {
            "enum": [
                "article",
                "package",
                "podcast",
                "video"
            ],
            "type": "string"
        }
    },
    "properties": {
        "author": {
            "type": "string"
        },
        "author_url": {
            "type": "string"
        },
        "categories": {
            "items": {
                "enum": [
                    "add_on",
                    "build_utility",
                    "data",
                    "educational",
                    "plugin",
                    "primitive",
                    "router",
                    "starters",
                    "testing",
                    "ui"
                ],
                "type": "string"
            },
            "type": "array"
        },
        "description": {
            "type": "string"
        },
        "keywords": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "link": {
            "format": "uri",
            "type": "string"
        },
        "official": {
            "type": "boolean"
        },
        "published_at": {
            "format": "date-time",
            "type": "string"
        },
        "title": {
            "minLength": 1,
            "type": "string"
        },
        "type": {
            "$ref": "#/definitions/EcosystemType"
        }
    },
    "type": "object"
}

=== solidjs/solidex/data/video/faq-why-doesnt-my-early-return-work-in-solid.json
{
  "link": "https://www.youtube.com/watch?v=Ilf34WjMBkU",
  "title": "FAQ: Why doesn't my early return work in Solid?",
  "description": "Dan explains why early returns don't work in Solid the same way they work in React",
  "keywords": [
    "faq",
    "early-return",
    "control-flow",
    "react"
  ],
  "author": "Dan Jutan (Jutanium)",
  "author_url": "https://twitter.com/jutanium",
  "type": "video",
  "categories": [
    "educational"
  ],
  "published_at": "2022-05-18T21:00:00.000Z",
  "official": true
}

=== solidjs/solidex/data/video/ryan-carniato--solidjs---getting-started-holyjs-2022.json
{
  "link": "https://www.youtube.com/watch?v=4KY8qIkJeSw",
  "title": "Ryan Carniato â€” SolidJS - Getting Started (HolyJS 2022)",
  "description": "In this talk, Ryan will introduce SolidJS a JavaScript UI framework built on fine-grained reactivity and compiled JSX.",
  "keywords": [
    "solid",
    "introduction",
    "ryanstreams",
    "holyjs"
  ],
  "author": "HolyJS",
  "author_url": "https://holyjs.ru/en",
  "type": "video",
  "categories": [
    "educational"
  ],
  "published_at": "2022-05-25T21:00:00.000Z"
}

=== solidjs/solidex/data/package/suid---material-ui.json
{
  "link": "https://suid.io",
  "title": "SUID - Material UI",
  "description": "A port of MUI built with SolidJS.",
  "author": "Juanra GM",
  "author_url": "https://github.com/juanrgm",
  "keywords": [
    "components",
    "material",
    "mui",
    "styled-component",
    "icons",
    "ui",
    "design"
  ],
  "official": false,
  "type": "package",
  "categories": [
    "ui",
    "add_on"
  ],
  "published_at": "2022-03-31T18:35:35.000Z"
}

=== solidjs/solidex/data/package/solidjs-treeview-component.json
{
  "link": "https://github.com/milahu/solidjs-treeview-component",
  "title": "solidjs-treeview-component",
  "description": "Interactive tree of nodes, expand/collapse, fetch child nodes on demand.",
  "author": "milahu",
  "author_url": "https://github.com/milahu",
  "keywords": [
    "tree",
    "expand",
    "collapse"
  ],
  "official": false,
  "type": "package",
  "categories": [
    "router"
  ]
}

=== solidjs/solidex/data/article/server-rendering-in-javascript-optimizing-performance.json
{
  "link": "https://dev.to/ryansolid/server-rendering-in-javascript-optimizing-performance-1jnk",
  "title": "Server Rendering in JavaScript: Optimizing Performance",
  "description": "Ryan discusses his learning process in topics of perf and optimization.",
  "author": "Ryan Carniato",
  "author_url": "https://www.github.com/ryansolid",
  "keywords": [
    ""
  ],
  "type": "article",
  "categories": [
    "educational"
  ],
  "published_at": "2021-02-25T15:34:41.000Z"
}

=== solidjs/solidex/data/article/introduction-to-solidjs.json
{
  "link": "https://blog.logrocket.com/introduction-solidjs/",
  "title": "Introduction to SolidJS",
  "description": "An introduction to the SolidJS library.",
  "author": "Iniubong Obonguko (LockRocket)",
  "author_url": "https://blog.logrocket.com/author/iniubongobonguko/",
  "keywords": [
    "introduction"
  ],
  "type": "article",
  "categories": [
    "educational"
  ],
  "published_at": "2021-11-10T19:55:10.000Z"
}

=== solidjs/solidex/data/package/solid-chart.json
{
  "link": "https://github.com/MrFoxPro/solid-chart.js",
  "title": "solid-chart",
  "description": "Chart.js powered by solid-js framework.",
  "author": "Dmitriy Nikiforov",
  "author_url": "https://github.com/MrFoxPro",
  "keywords": [
    "chart",
    "chart.js"
  ],
  "official": false,
  "type": "package",
  "categories": [
    "add_on"
  ]
}

=== solidjs/solidex/data/video/breaking-down-the-web-w-dan-jutan.json
{
  "link": "https://www.youtube.com/watch?v=REXtIuAJ3dE",
  "title": "Breaking Down the Web /w Dan Jutan",
  "description": "Dan Jutan, Solid Core Team member in charge of Documentation, joins Ryan to help give context for a lot of the topics he covers on stream.",
  "keywords": [
    "breaking down",
    "hydration",
    "ssr",
    "web",
    "streaming",
    "ryanstreams"
  ],
  "author": "Ryan Carniato",
  "author_url": "https://www.youtube.com/c/RyanCarniato9/videos",
  "type": "video",
  "categories": [
    "educational"
  ],
  "published_at": "2022-04-22T23:43:07.000Z"
}
